### ISSUE TITLE
Editor hangs on USB-connect (spinning snake)

### ISSUE THREAD

**Issue by bablokb** [circuitpython/web-editor#208] opened 2024-07-03 11:09 UTC
### CircuitPython Version

```python
Adafruit CircuitPython 9.1.0-beta.3-53-g1188d67263 on 2024-07-02; sunton_esp32_2432S032C with ESP32
```

### Workflow(s)

USB

### Browser(s)

```python
> google-chrome-stable --version
Google Chrome 126.0.6478.126 
```
```


### Console Log

```python
see below (description)
```

### Steps

1. Press USB on the selection box
2. Select the correct USB-device

### Description

The overlay with the spinning snake will stay for ever.

If I don't directly connect, but switch to the "Serial" tab and then press "Restart", the same happens but I can see that the browser *does* connect to the device.  In the screenshot you can see the title-bar and the output of my program from within the serial console.

![Bildschirmfoto_2024-07-03_12-13-33](https://github.com/circuitpython/web-editor/assets/9638355/94b7d31d-6179-4553-8754-bb90b809870d)

Browser console output:
![Bildschirmfoto_2024-07-03_13-06-09](https://github.com/circuitpython/web-editor/assets/9638355/7c5a341a-051e-4d84-9138-632f925e18d5)

**Comment by makermelissa** [comment] 2024-07-03 15:45
Duplicate of #203.

**Closed by makermelissa** 2024-07-03 15:45 UTC
Labels: bug, duplicate
